import { expect, test } from '@playwright/test'

test('runs new real samples, shows risk drivers, and validates inputs', async ({ page }) => {
  const errors: string[] = []
  const pythonRequests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (/\.py(?:\?|$)|pyodide/i.test(request.url())) pythonRequests.push(request.url()) })
  await page.goto('/projects/monte-carlo')
  await expect(page.getByRole('button', { name: 'What drives the risk?' })).toBeDisabled()
  await page.getByRole('button', { name: 'Run 10,000 futures' }).click()
  await expect(page.locator('.futures-density')).toHaveCount(3)
  const firstSample = await page.locator('.futures-density').first().getAttribute('d')
  await page.getByRole('button', { name: 'Run again' }).click()
  await expect(page.locator('.futures').getByRole('status')).toContainText('RUN 002')
  expect(await page.locator('.futures-density').first().getAttribute('d')).not.toEqual(firstSample)
  await expect(page.locator('.futures-summary')).toHaveCount(3)
  await expect(page.locator('.futures')).not.toContainText('NaN')
  await page.getByRole('button', { name: 'What drives the risk?' }).click()
  await expect(page.getByRole('img', { name: 'Chevrolet Bolt EV sensitivity ranking' })).toBeVisible()
  await expect(page.locator('.futures-tornado-row').first()).toContainText('Insurance')
  await page.getByRole('button', { name: 'CIVIC', exact: true }).click()
  await expect(page.getByRole('img', { name: 'Honda Civic LX sensitivity ranking' })).toBeVisible()
  await expect(page.locator('.futures-tornado-row').first()).toContainText('Gas price')
  await page.getByRole('button', { name: 'Back to distributions' }).click()
  expect(await page.locator('.futures-density').first().getAttribute('d')).not.toEqual(firstSample)
  await page.getByLabel('OWNERSHIP PERIOD', { exact: true }).fill('0')
  await page.getByRole('button', { name: 'Update model' }).click()
  expect(await page.getByLabel('OWNERSHIP PERIOD', { exact: true }).evaluate((element: HTMLInputElement) => element.validity.valid)).toBe(false)
  await expect(page.locator('.futures')).toHaveAttribute('data-running', 'false')
  expect(errors).toEqual([])
  expect(pythonRequests).toEqual([])
})

test('keyboard controls and reduced motion work on the project-page simulator', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/projects/monte-carlo#futures-simulator')
  await page.getByLabel('GAS PRICE', { exact: true }).focus()
  await page.keyboard.press('ArrowUp')
  await expect(page.getByLabel('GAS PRICE', { exact: true })).toHaveValue('3.41')
  await page.getByRole('button', { name: 'Run 10,000 futures' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('img', { name: /8-year vehicle NPV distributions/ })).toBeVisible()
  await expect(page.locator('.futures-distributions')).toHaveCSS('animation-name', 'none')
  await page.getByRole('button', { name: 'What drives the risk?' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('img', { name: /Chevrolet Bolt EV sensitivity ranking/ })).toBeVisible()
})

test('charts and controls remain readable across desktop, tablet, and mobile', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const width of [1440, 1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/projects/monte-carlo')
    await page.getByRole('button', { name: 'Run 10,000 futures' }).click()
    await expect(page.locator('.futures').getByRole('status')).toContainText('RUN 001')
    const chart = page.locator('.futures-chart')
    expect((await chart.boundingBox())!.height).toBeGreaterThan(210)
    for (const input of await page.locator('.futures-field input').all()) expect((await input.boundingBox())!.height).toBeGreaterThanOrEqual(44)
    const overflow = await page.locator('.futures').evaluate(element => Array.from(element.querySelectorAll<HTMLElement>('.futures-summary, .futures-controls, .futures-plot-heading'))
      .filter(node => node.scrollWidth > node.clientWidth + 1).map(node => node.className))
    expect(overflow).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    if ([1440, 390].includes(width)) await page.locator('.project-detail').screenshot({ path: test.info().outputPath(`futures-${width}.png`) })
    await page.getByRole('button', { name: 'What drives the risk?' }).click()
    await expect(page.locator('.futures-tornado-row')).toHaveCount(4)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    if ([1440, 390].includes(width)) await page.locator('.futures').screenshot({ path: test.info().outputPath(`sensitivity-${width}.png`) })
  }
})
