import { expect, test } from '@playwright/test'

test('input walkthrough plays inline at 5× and pauses when hidden or manually paused', async ({ page }) => {
  await page.goto('/')
  await page.locator('#pentimento').scrollIntoViewIfNeeded()
  const video = page.locator('#pentimento video')
  await expect(video).toBeVisible()
  await expect(video).toHaveAttribute('preload', 'metadata')
  await expect(video).toHaveAttribute('playsinline', '')
  await expect(video).toHaveJSProperty('muted', true)
  await expect(video).toHaveJSProperty('loop', true)
  await expect(video).toHaveJSProperty('controls', false)
  await expect.poll(() => video.evaluate(element => (element as HTMLVideoElement).readyState), { timeout: 20000 }).toBeGreaterThanOrEqual(2)
  await expect(video).toHaveJSProperty('playbackRate', 5)
  await expect(video).toHaveJSProperty('paused', false)
  await page.getByRole('button', { name: 'Pause input video' }).click()
  await expect(video).toHaveJSProperty('paused', true)
  await page.getByRole('button', { name: 'Play input video' }).click()
  await expect(video).toHaveJSProperty('paused', false)
  await page.locator('footer').scrollIntoViewIfNeeded()
  await expect(video).toHaveJSProperty('paused', true)
  await video.scrollIntoViewIfNeeded()
  await expect(video).toHaveJSProperty('paused', false)
})

test('failed reconstruction offers retry and keeps the input available', async ({ page }) => {
  await page.route('**/Textured_mesh_1.*.glb', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/projects/pentimento')
  await page.getByRole('tab', { name: 'FINAL MODEL' }).click()
  await expect(page.getByText('RECONSTRUCTION COULD NOT BE LOADED.')).toBeVisible()
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByText('RECONSTRUCTION COULD NOT BE LOADED.')).toBeVisible()
  await page.getByRole('tab', { name: 'INPUT VIDEO' }).click()
  await expect(page.locator('video')).toHaveJSProperty('paused', false)
})

test('homepage trace fits the viewport and Pentimento retains its measured frame', async ({ page }) => {
  for (const [width, pentimentoHeight] of [[1440, 590], [1024, 590], [768, 590], [390, 520.796875], [320, 524.796875]]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/')
    await page.locator('#argus').scrollIntoViewIfNeeded()
    await expect(page.locator('.argus-preview-stage')).toBeVisible()
    const argus = await page.locator('.argus-preview-stage').boundingBox()
    expect(argus!.width).toBeLessThanOrEqual(width)
    await expect(page.locator('iframe')).toHaveCount(0)
    await page.locator('#pentimento').scrollIntoViewIfNeeded()
    await expect(page.locator('.pentimento-experience')).toBeVisible()
    const pentimento = await page.locator('.pentimento-experience').boundingBox()
    expect(Math.abs(pentimento!.height - pentimentoHeight)).toBeLessThan(1)
    await expect(page.getByRole('tab', { name: 'INPUT VIDEO' })).toHaveAttribute('aria-selected', 'true')
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  }
})

test.describe('touch reconstruction', () => {
  test.use({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' })

  test('mobile touch orbit and pinch work while vertical swipes can scroll @real-media', async ({ page }) => {
    test.setTimeout(120000)
    await page.goto('/projects/pentimento')
    await page.getByRole('tab', { name: 'FINAL MODEL' }).tap()
    const viewer = page.getByRole('group', { name: /Interactive Pentimento reconstruction/ })
    await expect(viewer).toHaveAttribute('data-model-state', 'ready', { timeout: 90000 })
    await viewer.scrollIntoViewIfNeeded()
    const canvas = viewer.locator('canvas')
    await expect(canvas).toHaveCSS('touch-action', 'pan-y')
    const box = (await canvas.boundingBox())!
    const x = box.x + box.width / 2
    const y = box.y + box.height / 2
    const session = await page.context().newCDPSession(page)
    const touch = (type: string, points: { x: number; y: number; id: number }[]) => session.send('Input.dispatchTouchEvent', { type: type as 'touchStart' | 'touchMove' | 'touchEnd', touchPoints: points })
    const beforeOrbit = await canvas.screenshot()
    await touch('touchStart', [{ x: x - 45, y, id: 0 }])
    for (let step = 1; step <= 5; step++) await touch('touchMove', [{ x: x - 45 + step * 18, y, id: 0 }])
    await touch('touchEnd', [])
    await expect.poll(() => canvas.screenshot()).not.toEqual(beforeOrbit)
    const beforeZoom = await canvas.screenshot()
    await touch('touchStart', [{ x: x - 25, y, id: 0 }, { x: x + 25, y, id: 1 }])
    for (let step = 1; step <= 5; step++) await touch('touchMove', [{ x: x - 25 - step * 8, y, id: 0 }, { x: x + 25 + step * 8, y, id: 1 }])
    await touch('touchEnd', [])
    await expect.poll(() => canvas.screenshot()).not.toEqual(beforeZoom)
    await page.getByRole('button', { name: 'Reset view' }).tap()
    const scrollBefore = await page.evaluate(() => window.scrollY)
    await touch('touchStart', [{ x, y: y + 80, id: 0 }])
    for (let step = 1; step <= 6; step++) await touch('touchMove', [{ x, y: y + 80 - step * 25, id: 0 }])
    await touch('touchEnd', [])
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(scrollBefore)
    await page.getByRole('tab', { name: 'FINAL MODEL' }).scrollIntoViewIfNeeded()
    await page.locator('.project-detail').screenshot({ path: test.info().outputPath('pentimento-mobile-model.png') })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
    await session.detach()
  })
})
