import { memo, type CSSProperties, type ReactNode } from 'react'
import { CDFChart, Distribution, Paths } from './AnimationCharts'
import { vehicleLabels, demonstrationConfig, type Demonstration } from './scenario'
import { annualEnergyCost } from './simulation'
import { clamp01, type SceneId } from './timeline'
import { currency } from './visualization'

const money = (value: number, digits = 2) => `${value < 0 ? '−' : ''}$${Math.abs(value).toLocaleString('en-US', { minimumFractionDigits: digits, maximumFractionDigits: digits })}`
function Reveal({ at, progress, children }: { at: number; progress: number; children: ReactNode }) {
  return <div className="ff-reveal" data-revealed={progress >= at} style={{ visibility: progress >= at ? 'visible' : 'hidden' }}>{children}</div>
}
function Metric({ label, value, gold = false }: { label: string; value: string; gold?: boolean }) {
  return <div className={`ff-metric${gold ? ' ff-gold' : ''}`}><dt>{label}</dt><dd>{value}</dd></div>
}
function Normal({ label, mean, sd }: { label: string; mean: string; sd: string }) {
  return <div className="ff-normal"><div><strong>{label}</strong><span>μ {mean} / σ {sd}</span></div><svg viewBox="0 0 140 50" aria-hidden="true"><path d="M2 46 C30 46 39 43 48 23 C56 2 63 2 70 2 C83 2 87 19 93 30 C105 47 113 46 138 46" fill="none" stroke="currentColor" strokeWidth="2"/><line x1="2" x2="138" y1="46" y2="46" stroke="currentColor" opacity=".2"/></svg></div>
}
const framework = ['UNCERTAINTY', 'SIMULATION', 'NPV DISTRIBUTION', 'TAIL RISK', 'STOCHASTIC COMPARISON', 'SENSITIVITY', 'DECISION']

export const AnimationScene = memo(function AnimationScene({ id, progress, reduced, data }: { id: SceneId; progress: number; reduced: boolean; data: Demonstration }) {
  const trace = data.trace
  const year = trace.years[0]
  const bolt = data.bolt
  const stats = bolt.statistics
  const model = demonstrationConfig.assumptions
  const energy = annualEnergyCost(bolt.vehicle, model.mileage, year.energyPrice)
  const steady = (p: number) => reduced ? p > 0 ? 1 : 0 : p
  switch (id) {
    case 'SETUP': return <div className="ff-intro"><span className="ff-kicker">STOCHASTIC DECISION MODEL</span><div className="ff-display">10,000<br/><em>FUTURES</em></div><p>Which vehicle carries the least<br/>eight-year financial risk?</p><div className="ff-vehicles">{vehicleLabels.map((label, i) => <Reveal key={label} at={i * .15} progress={progress}><span><i className={`ff-dot ff-dot-${i}`}/>{label}</span></Reveal>)}</div></div>
    case 'INPUTS': return <><div className="ff-two-columns"><div className="ff-panel"><span className="ff-kicker">BOLT EV / FIXED ASSUMPTIONS</span><dl className="ff-fields"><Metric label="Purchase price" value={money(bolt.vehicle.purchasePrice)}/><Metric label="Loan / 5 annual payments" value={money(bolt.vehicle.loanPayment)}/><Metric label="Annual mileage" value="12,000 mi"/><Metric label="Ownership" value="8 years"/><Metric label="Resale / purchase price" value="30%"/><Metric label="Discount / inflation" value="6% / 2%"/></dl></div><div className="ff-panel"><span className="ff-kicker">INDEPENDENT NORMAL DRAWS</span><Reveal at={.12} progress={progress}><Normal label="Electricity / kWh" mean="$0.25" sd="$0.05"/></Reveal><Reveal at={.3} progress={progress}><Normal label="Annual maintenance" mean="$400" sd="$80"/></Reveal><Reveal at={.48} progress={progress}><Normal label="Annual insurance" mean="$1,400" sd="$280"/></Reveal></div></div><p className="ff-note">Fixed assumptions define the model. Uncertain costs vary each year.</p></>
    case 'ONE_FUTURE': return <><div className="ff-draws"><Reveal at={0} progress={progress}><dl><Metric label="Electricity / kWh" value={money(year.energyPrice, 4)} gold/></dl></Reveal><Reveal at={.12} progress={progress}><dl><Metric label="Maintenance" value={money(year.maintenance)} gold/></dl></Reveal><Reveal at={.24} progress={progress}><dl><Metric label="Insurance" value={money(year.insurance)} gold/></dl></Reveal></div><Reveal at={.36} progress={progress}><div className="ff-equation"><span>12,000 mi ÷ 100 × 28 kWh</span><span>× {money(year.energyPrice, 4)} / kWh</span><strong>= {money(energy)} electricity / year</strong></div></Reveal><Reveal at={.58} progress={progress}><div className="ff-cashflow"><span>LOAN {money(bolt.vehicle.loanPayment)}</span><span>+ ENERGY {money(energy)}</span><span>+ MAINTENANCE {money(year.maintenance)}</span><span>+ INSURANCE {money(year.insurance)}</span></div></Reveal><Reveal at={.75} progress={progress}><div className="ff-result"><span>YEAR 1 CASH FLOW</span><strong>{money(year.cashFlow)}</strong></div></Reveal><p className="ff-note">Actual sample 001 · costs are outflows · displayed values rounded</p></>
    case 'FULL_PATH': return <><div className="ff-year-grid"><div className="ff-year"><span>Y0</span><strong>{currency(trace.initialCashFlow)}</strong><small>10% down payment</small></div>{trace.years.map((item, i) => <div key={item.year} className="ff-year" style={{ opacity: progress >= i / 12 ? 1 : .18 }}><span>Y{item.year}</span><strong>{currency(item.cashFlow)}</strong><small>{item.year === 8 ? `Includes ${currency(bolt.vehicle.purchasePrice * .3)} resale` : item.year <= 5 ? 'Loan + annual costs' : 'Loan complete'}</small></div>)}</div><div className="ff-equation ff-equation-small"><span>Recurring costs × 1.02<sup>year − 1</sup></span><span>− loan + terminal resale</span></div><p className="ff-note">New independent draws every year. One possible financial history.</p></>
    case 'DISCOUNT': return <><div className="ff-equation"><span>Annual cash flow × <b>1 / (1.06)<sup>t</sup></b></span></div><Paths data={data} progress={steady(progress)} reduced={reduced} discount/><div className="ff-discount-steps">{[1, 4, 8].map((t, i) => <Reveal key={t} at={i * .2} progress={progress}><span>Y{t} · {currency(trace.years[t - 1].cashFlow)} ÷ 1.06<sup>{t}</sup></span><strong>{currency(trace.years[t - 1].discounted)}</strong></Reveal>)}</div><Reveal at={.65} progress={progress}><div className="ff-result"><span>Y0 + Σ DISCOUNTED CASH FLOWS</span><strong>{money(trace.npv)} <small>ONE NPV</small></strong></div></Reveal></>
    case 'REPEAT': {
      const count = [1, 10, 100, 1000, 10000][Math.min(4, Math.floor(progress * 5))]
      return <><div className="ff-counter">{count.toLocaleString('en-US')}<span>POSSIBLE EIGHT-YEAR FUTURES</span></div><Paths data={data} progress={reduced ? Math.min(1, count / 128) : progress} reduced={reduced}/><p className="ff-example">One example—not a prediction.</p><p className="ff-note">128 representative paths shown · all 10,000 outcomes calculated</p></>
    }
    case 'HISTOGRAM': return <><div className="ff-transformation"><span>10,000 PATHS</span><i>→</i><span>10,000 NPVs</span><i>→</i><span>48 BINS</span></div><Distribution data={data} progress={steady(clamp01(progress * 1.3))} particles={!reduced} markers={[{ label: 'Example NPV', value: trace.npv, gold: true }]}/><div className="ff-result"><span>ONE SAMPLE BECOMES ONE OBSERVATION</span><strong className="ff-gold">{money(trace.npv)}</strong></div><p className="ff-note">Every outcome counts. Bar height shows the number of futures in each interval.</p></>
    case 'ANATOMY': {
      const markers = [{ label: '5th percentile', value: stats.var5 }, { label: 'Median', value: bolt.median, gold: true }, { label: '95th percentile', value: bolt.p95 }, { label: 'Mean', value: stats.mean, gold: true }]
      return <><Distribution data={data} markers={markers.filter((_, i) => progress >= i * .21)}/><dl className="ff-four-metrics">{markers.map((marker, i) => <Reveal key={marker.label} at={i * .21} progress={progress}><Metric label={marker.label} value={currency(marker.value)}/></Reveal>)}</dl><p className="ff-note">Negative NPV is present ownership cost. Higher NPV means lower cost.</p></>
    }
    case 'VAR': return <><Distribution data={data} tail markers={[{ label: 'VaR', value: stats.var5 }]}/><div className="ff-risk-explanation"><strong>VaR 5% <span>{money(stats.var5)}</span></strong><p>The cutoff separating the worst 5% of outcomes.</p></div><p className="ff-note">← Worse outcomes · 5th-percentile NPV · higher NPV is better →</p></>
    case 'CVAR': return <><Distribution data={data} tail tailProgress={reduced ? undefined : progress} markers={[{ label: 'VaR', value: stats.var5 }, ...(progress > .58 ? [{ label: 'CVaR', value: stats.cvar5, gold: true }] : [])]}/><div className="ff-tail-equation"><div><span>WORST 5%</span><strong>{data.tail.length} futures</strong></div><span aria-hidden="true">→</span><Reveal at={.2} progress={progress}><span>Σ tail NPVs / {data.tail.length}</span><strong>{currency(data.tail.reduce((a, b) => a + b, 0))} / {data.tail.length}</strong></Reveal><span aria-hidden="true">→</span><Reveal at={.58} progress={progress}><span>CVaR / TAIL MEAN</span><strong>{money(stats.cvar5)}</strong></Reveal></div><p className="ff-note">VaR marks the cutoff. CVaR averages the outcomes at or below it.</p></>
    case 'VEHICLES': return <><div className="ff-comparison-grid">{data.results.map((result, i) => <div key={result.vehicle.id} className="ff-vehicle-distribution"><h4><i className={`ff-dot ff-dot-${i}`}/>{vehicleLabels[i]}</h4><Distribution data={data} index={i} shared progress={steady(clamp01(progress * 3 - i * .35))}/><dl><Metric label="Mean NPV" value={currency(result.statistics.mean)}/><Metric label="VaR 5%" value={currency(result.statistics.var5)}/><Metric label="CVaR" value={currency(result.statistics.cvar5)}/></dl></div>)}</div><p className="ff-note">10,000 futures per vehicle · identical horizontal and vertical scales</p></>
    case 'COMPARISON': return <><div className="ff-vehicles ff-legend">{vehicleLabels.map((label, i) => <span key={label}><i className={`ff-dot ff-dot-${i}`}/>{label}</span>)}</div><CDFChart data={data} progress={steady(clamp01(progress * 2))}/><div className="ff-cdf-explanation"><span>ACCUMULATE OUTCOMES ≤ NPV → CUMULATIVE PROBABILITY</span><p>A lower CDF means fewer outcomes below that NPV.</p></div><Reveal at={.5} progress={progress}><div className="ff-dominance">{data.comparisons.map(item => <span key={item.pair}>{item.text}</span>)}</div></Reveal><p className="ff-note">Empirical comparisons in this sample, under these assumptions.</p></>
    case 'SENSITIVITY': {
      const max = data.sensitivity[0].impact
      return <><div className="ff-sensitivity-heading"><span>BOLT EV / ONE INPUT AT A TIME</span><span>−10% ← BASELINE → +10%</span></div><div className="ff-tornado">{data.sensitivity.map((driver, i) => <div className="ff-tornado-row" key={driver.key}><span>{driver.label}</span><div className="ff-tornado-track"><i style={{ '--bar': `${Math.abs(driver.highDelta) / max * 48 * steady(clamp01(progress * 2 - i * .18))}%`, '--color': driver.highDelta < 0 ? '#74775d' : '#b38a37' } as CSSProperties}/><i style={{ '--bar': `${Math.abs(driver.lowDelta) / max * 48 * steady(clamp01(progress * 2 - i * .18))}%`, '--color': driver.lowDelta > 0 ? '#b38a37' : '#74775d' } as CSSProperties}/></div><span>±{currency(driver.impact)}</span></div>)}</div><div className="ff-chart-axis"><span>← LOWER MEAN NPV</span><span>HIGHER MEAN NPV →</span></div><p className="ff-note">Gold: input −10% · olive: input +10%. Resale 30% → 27% / 33%.<br/>Exact expected NPV; other inputs held fixed.</p></>
    }
    case 'FRAMEWORK': return <div className="ff-finale"><p>A framework for decisions.<br/>Not a prediction of the future.</p><ol>{framework.map((step, i) => <li key={step} style={{ opacity: reduced || progress >= i / 12 ? 1 : .18 }}><span>{String(i + 1).padStart(2, '0')}</span>{step}</li>)}</ol><span className="ff-kicker">CHANGE THE ASSUMPTIONS. EXPLORE THE TRADEOFFS.</span></div>
  }
})
